use_frameworks!

platform :ios, '12.0'

target 'WolfGraph_Example' do
  pod 'WolfGraph', :path => '../'
  pod 'WolfKit' #, :path => '../../WolfViews'

  target 'WolfGraph_Tests' do
    inherit! :search_paths
  end
end
